### ISSUE TITLE
Error when setting LABEL_SIZE

### ISSUE THREAD

**Issue by lordhelmet77** [sam159/brotherql_grocylabels#1]
I only have 62mm endless and 29x90 to go with. So I'm setting the label-size as environment variable.
My compose for grocylabels:

```
  grocylabels:
    image: sam159/brotherql_grocylabels:latest
    restart: unless-stopped
    environment:
      - PRINTER_MODEL=QL-720NW
      - PRINTER_PATH=tcp://10.16.0.20
      - LABEL_SIZE=29x90
    networks:
      - lab01
    ports:
      - 8000:8000
```

If I set any LABEL_SIZE, I get a CODE 400 due to timeout:
```
  "error_message": "cURL error 28: Operation timed out after 2001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://10.16.0.12:8000/print"
```
If I don't set LABEL_SIZE, the print is sent but the printer gives an error for wrong paper size.

Am I missing something?

The printer works fine, for example printing from the brother_ql_web-dashboard works flawless.
